fixup! feat(packaging): refactor install script to use software repositories
Signed-off-by: Reuben Miller <reuben.d.miller@gmail.com>

diff --git a/configuration/package_scripts/_generated/tedge-mapper/deb/postinst b/configuration/package_scripts/_generated/tedge-mapper/deb/postinst
--- a/configuration/package_scripts/_generated/tedge-mapper/deb/postinst
+++ b/configuration/package_scripts/_generated/tedge-mapper/deb/postinst
@@ -69,6 +69,16 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	deb-systemd-helper update-state tedge-mapper-collectd.service >/dev/null || true
 fi
 # End automatically added section
+# Automatically added by thin-edge.io
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			deb-systemd-invoke try-restart tedge-mapper-aws.service tedge-mapper-az.service tedge-mapper-c8y.service tedge-mapper-collectd.service >/dev/null || true
+		fi
+	fi
+fi
+# End automatically added section
 
 enable_start_service() {
     name="$1"
