feat(install): support user and group management using adduser or useradd for improved compatibility
Signed-off-by: Reuben Miller <reuben.d.miller@gmail.com>

diff --git a/configuration/debian/tedge/postrm b/configuration/debian/tedge/postrm
--- a/configuration/debian/tedge/postrm
+++ b/configuration/debian/tedge/postrm
@@ -1,15 +1,31 @@
 #!/bin/sh
 set -e
 
+command_exists() {
+    command -V "$1" >/dev/null 2>&1
+}
+
 remove_user_tedge() {
     if getent passwd tedge > /dev/null; then
-        deluser --quiet --system tedge
+        if command_exists userdel; then
+            userdel tedge
+        elif command_exists deluser; then
+            deluser tedge
+        else
+            echo "WARNING: Could not delete group: tedge" >&2
+        fi
     fi
 }
 
 remove_tedge_group() {
     if getent group tedge > /dev/null; then
-        groupdel tedge
+        if command_exists groupdel; then
+            groupdel tedge
+        elif command_exists delgroup; then
+            delgroup tedge
+        else
+            echo "WARNING: Could not delete group: tedge" >&2
+        fi
     fi
 }
 
diff --git a/configuration/debian/tedge/preinst b/configuration/debian/tedge/preinst
--- a/configuration/debian/tedge/preinst
+++ b/configuration/debian/tedge/preinst
@@ -1,15 +1,31 @@
 #!/bin/sh
 set -e
 
+command_exists() {
+    command -V "$1" >/dev/null 2>&1
+}
+
 ### Create groups
 if ! getent group tedge >/dev/null; then
-    groupadd --system tedge
+    if command_exists groupadd; then
+        groupadd --system tedge
+    elif command_exists addgroup; then
+        addgroup -S tedge
+    else
+        echo "WARNING: Could not create group: tedge" >&2
+    fi
 fi
 
 ### Create users
 # Create user tedge with no home(--no-create-home), no login(--shell) and in group tedge(--gid)
 if ! getent passwd tedge >/dev/null; then
-    useradd --system --no-create-home --shell /sbin/nologin --gid tedge tedge
+    if command_exists useradd; then
+        useradd --system --no-create-home --shell /sbin/nologin --gid tedge tedge
+    elif command_exists adduser; then
+        adduser -g "" -H -D tedge -G tedge
+    else
+        echo "WARNING: Could not create user: tedge" >&2
+    fi
 fi
 
 ### Create file in /etc/sudoers.d directory. With this configuration, the tedge user have the right to call the tedge command with sudo rights, which is required for system-wide configuration in "/etc/tedge"
