fix(install): avoid sudo usage in maintainer scripts
Maintainer scripts already run as root and it just add unneeded dependency on sudo

Signed-off-by: Reuben Miller <reuben.d.miller@gmail.com>

diff --git a/configuration/debian/tedge/preinst b/configuration/debian/tedge/preinst
--- a/configuration/debian/tedge/preinst
+++ b/configuration/debian/tedge/preinst
@@ -42,46 +42,48 @@ fi
 # as there is only `tedge` user exists.
 
 if [ -d "/etc/tedge/operations/c8y" ]; then
-    sudo chown tedge:tedge /etc/tedge/operations/c8y
-    sudo chown tedge:tedge /etc/tedge/operations/c8y/c8y_*
+    chown tedge:tedge /etc/tedge/operations/c8y
+
+    # Don't fail if there are no files found
+    chown tedge:tedge /etc/tedge/operations/c8y/c8y_* 2>/dev/null ||:
 fi
 
 if [ -d "/etc/tedge/operations/az" ]; then
-    sudo chown tedge:tedge /etc/tedge/operations/az
+    chown tedge:tedge /etc/tedge/operations/az
 fi
 
 if [ -d "/etc/tedge/operations/aws" ]; then
-    sudo chown tedge:tedge /etc/tedge/operations/aws
+    chown tedge:tedge /etc/tedge/operations/aws
 fi
 
 if [ -d "/etc/tedge/.agent/" ]; then
-    sudo chown tedge:tedge /etc/tedge/.agent
+    chown tedge:tedge /etc/tedge/.agent
 fi
 
 if [ -d "/var/log/tedge/agent/" ]; then
-    sudo chown tedge:tedge /var/log/tedge/agent
+    chown tedge:tedge /var/log/tedge/agent
 fi
 
 if [ -f "/run/lock/tedge_agent.lock" ]; then
-    sudo chown tedge:tedge /run/lock/tedge_agent.lock
+    chown tedge:tedge /run/lock/tedge_agent.lock
 fi
 
 if [ -f "/run/lock/tedge-agent.lock" ]; then
-    sudo chown tedge:tedge /run/lock/tedge-agent.lock
+    chown tedge:tedge /run/lock/tedge-agent.lock
 fi
 
 if [ -f "/run/lock/tedge-mapper-c8y.lock" ]; then
-    sudo chown tedge:tedge /run/lock/tedge-mapper-c8y.lock
+    chown tedge:tedge /run/lock/tedge-mapper-c8y.lock
 fi
 
 if [ -f "/run/lock/tedge-mapper-az.lock" ]; then
-    sudo chown tedge:tedge /run/lock/tedge-mapper-az.lock
+    chown tedge:tedge /run/lock/tedge-mapper-az.lock
 fi
 
 if [ -f "/run/lock/tedge-mapper-aws.lock" ]; then
-    sudo chown tedge:tedge /run/lock/tedge-mapper-aws.lock
+    chown tedge:tedge /run/lock/tedge-mapper-aws.lock
 fi
 
 if [ -f "/run/lock/tedge-mapper-collectd.lock" ]; then
-    sudo chown tedge:tedge /run/lock/tedge-mapper-collectd.lock
+    chown tedge:tedge /run/lock/tedge-mapper-collectd.lock
 fi
