fix: move text filtering from log plugin to agent

diff --git a/tests/RobotFramework/tests/cumulocity/log/plugins/journald b/tests/RobotFramework/tests/cumulocity/log/plugins/journald
--- a/tests/RobotFramework/tests/cumulocity/log/plugins/journald
+++ b/tests/RobotFramework/tests/cumulocity/log/plugins/journald
@@ -6,19 +6,17 @@ usage() {
     echo "Usage: $0 <command> [args...]"
     echo "Commands:"
     echo "  list                                List all log types supported by this plugin"
-    echo "  get <type>                          Get logs for the specified type"
+    echo "  get <log-type>                      Get logs for the specified type"
     echo "      [--since <timestamp>]"
     echo "      [--until <timestamp>]"
-    echo "      [--filter <text-filter>]"
     echo "      [--tail <lines-from-end>]"
     exit 1
 }
 
 list_log_types() {
-    echo ":::begin-tedge:::"
     systemctl list-units --type=service --no-legend --no-pager --plain \
+        | grep -v "^systemd" \
         | awk '{ sub(/\.service$/, "", $1); print $1 }'
-    echo ":::end-tedge:::"
 }
 
 get_logs() {
@@ -27,7 +25,6 @@ get_logs() {
     
     local since_arg=""
     local until_arg=""
-    local filter_arg=""
     local tail_arg=""
     
     while [[ $# -gt 0 ]]; do
@@ -38,10 +35,6 @@ get_logs() {
                 ;;
             --until)
                 until_arg="--until=@$2"
-                shift 2
-                ;;
-            --filter)
-                filter_arg="$2"
                 shift 2
                 ;;
             --tail)
@@ -69,14 +62,7 @@ get_logs() {
         cmd="$cmd $tail_arg"
     fi
     
-    # Execute journalctl and apply text filter if specified
-    echo ":::begin-tedge:::"
-    if [[ -n "$filter_arg" ]]; then
-        eval "$cmd" | grep -i "$filter_arg"
-    else
-        eval "$cmd"
-    fi
-    echo ":::end-tedge:::"
+    eval "$cmd"
 }
 
 main() {
@@ -93,7 +79,7 @@ main() {
             ;;
         "get")
             if [[ $# -lt 1 ]]; then
-                echo "Error: 'get' command expects a mandatory <type> arguments" >&2
+                echo "Error: 'get' command expects a mandatory <log-type> arguments" >&2
                 usage
             fi
             get_logs "$@"
