generate changelog from tags and don't block a release in case of unexpected errors
Signed-off-by: Reuben Miller <reuben.d.miller@gmail.com>

diff --git a/.github/workflows/build-workflow.yml b/.github/workflows/build-workflow.yml
--- a/.github/workflows/build-workflow.yml
+++ b/.github/workflows/build-workflow.yml
@@ -441,7 +441,9 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          just generate-changelog
+          if ! just generate-changelog --from-tags; then
+            echo "Warning: Failed to generate changelog, but it should not block a release" > _CHANGELOG.md
+          fi
       - name: Release
         uses: softprops/action-gh-release@v2
         env:
